package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/piotrekmonko/portfello/pkg/dao"
	"github.com/piotrekmonko/portfello/pkg/graph/model"
)

// UserCreate is the resolver for the userCreate field.
func (r *mutationResolver) UserCreate(ctx context.Context, input model.NewUser) (*dao.User, error) {
	panic(fmt.Errorf("not implemented: UserCreate - userCreate"))
}

// UserAssignRoles is the resolver for the userAssignRoles field.
func (r *mutationResolver) UserAssignRoles(ctx context.Context, input []string) ([]*model.Role, error) {
	panic(fmt.Errorf("not implemented: UserAssignRoles - userAssignRoles"))
}

// UserRoles is the resolver for the userRoles field.
func (r *queryResolver) UserRoles(ctx context.Context, userID string) ([]model.RoleID, error) {
	panic(fmt.Errorf("not implemented: UserRoles - userRoles"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*dao.User, error) {
	return r.DbQueries.UsersList(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
