package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/piotrekmonko/portfello/pkg/dao"
	"github.com/piotrekmonko/portfello/pkg/graph/model"
)

// UserCreate is the resolver for the userCreate field.
func (r *mutationResolver) UserCreate(ctx context.Context, input model.NewUser) (*dao.User, error) {
	panic(fmt.Errorf("not implemented: UserCreate - userCreate"))
}

// UserAssignRoles is the resolver for the userAssignRoles field.
func (r *mutationResolver) UserAssignRoles(ctx context.Context, input []string) ([]*model.Role, error) {
	panic(fmt.Errorf("not implemented: UserAssignRoles - userAssignRoles"))
}

// UserGetRoles is the resolver for the userGetRoles field.
func (r *mutationResolver) UserGetRoles(ctx context.Context, userID string) ([]model.RoleID, error) {
	panic(fmt.Errorf("not implemented: UserGetRoles - userGetRoles"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*dao.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Email is the resolver for the email field.
func (r *userResolver) Email(ctx context.Context, obj *dao.User) (string, error) {
	panic(fmt.Errorf("not implemented: Email - email"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
