// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/piotrekmonko/portfello/pkg/auth"
)

type Operation interface {
	IsOperation()
	GetID() string
	GetWalletID() string
	GetAmount() float64
	GetDescription() *string
	GetCreatedAt() time.Time
}

type CreateWalletInput struct {
	Currency string `json:"currency"`
}

type Mutation struct {
}

type NewUser struct {
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
}

type Query struct {
}

type Role struct {
	UserID string      `json:"userId"`
	Role   auth.RoleID `json:"role"`
}
