// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/piotrekmonko/portfello/pkg/auth"
)

type NewUser struct {
	Email       string        `json:"email"`
	DisplayName string        `json:"displayName"`
	Roles       []auth.RoleID `json:"roles"`
}

type Role struct {
	UserID string      `json:"userId"`
	Role   auth.RoleID `json:"role"`
}
