// Code generated by mockery v2.40.3. DO NOT EDIT.

package mock_dao

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// Mockbeginner is an autogenerated mock type for the beginner type
type Mockbeginner struct {
	mock.Mock
}

type Mockbeginner_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockbeginner) EXPECT() *Mockbeginner_Expecter {
	return &Mockbeginner_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *Mockbeginner) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockbeginner_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type Mockbeginner_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *Mockbeginner_Expecter) BeginTx(ctx interface{}, opts interface{}) *Mockbeginner_BeginTx_Call {
	return &Mockbeginner_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *Mockbeginner_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *Mockbeginner_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *Mockbeginner_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *Mockbeginner_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockbeginner_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *Mockbeginner_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbeginner creates a new instance of Mockbeginner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbeginner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockbeginner {
	mock := &Mockbeginner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
