// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dao

import (
	"time"
)

type History struct {
	ID        string
	Event     string
	Email     string
	CreatedAt time.Time
}
