// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dao

import (
	"context"
)

type Querier interface {
	UsersList(ctx context.Context) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
