// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package dao

import (
	"context"
)

type Querier interface {
	ExpenseInsert(ctx context.Context, arg *ExpenseInsertParams) error
	ExpenseListByWallet(ctx context.Context, walletID string) ([]*Expense, error)
	ExpenseListByWalletByUser(ctx context.Context, walletID string, userID string) ([]*Expense, error)
	HistoryInsert(ctx context.Context, arg *HistoryInsertParams) error
	HistoryList(ctx context.Context) ([]*History, error)
	WalletInsert(ctx context.Context, arg *WalletInsertParams) error
	WalletUpdateBalance(ctx context.Context, balance float64, iD string) error
	WalletsByUser(ctx context.Context, userID string) ([]*Wallet, error)
}

var _ Querier = (*Queries)(nil)
