// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: queries.sql

package dao

import (
	"context"
)

const historyList = `-- name: HistoryList :many
SELECT id, event, email, created_at FROM history ORDER BY id
`

func (q *Queries) HistoryList(ctx context.Context) ([]*History, error) {
	rows, err := q.db.QueryContext(ctx, historyList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Event,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
